import {
  Inbox, Truck, Users, BarChart2, Settings, Search, Bell, Plus, Filter,
  Download, Check, X, ArrowRight, ArrowUp, ArrowDown, Calendar, MoreHorizontal,
  Link, Copy, Flag, FileText, Camera, ChevronRight, ArrowLeft, Home, User,
  DollarSign, Upload, MessageSquare, Sparkles, History, Hash,
  Car, Building2, Laptop, Cog, Package,
} from 'lucide-react';

const P = { size: 16, strokeWidth: 1.75, className: 'ic' } as const;
const MP = { size: 20, strokeWidth: 2 } as const;

export const I = {
  inbox:    <Inbox    {...P} />,
  truck:    <Truck    {...P} />,
  users:    <Users    {...P} />,
  chart:    <BarChart2 {...P} />,
  slack:    <Hash     {...P} />,
  settings: <Settings {...P} />,
  search:   <Search   {...P} />,
  bell:     <Bell     {...P} />,
  plus:     <Plus     {...P} />,
  filter:   <Filter   {...P} />,
  download: <Download {...P} />,
  check:    <Check    {...P} />,
  x:        <X        {...P} />,
  arrowR:   <ArrowRight  {...P} />,
  arrowUp:  <ArrowUp     {...P} />,
  arrowDn:  <ArrowDown   {...P} />,
  cal:      <Calendar    {...P} />,
  more:     <MoreHorizontal {...P} />,
  link:     <Link     {...P} />,
  copy:     <Copy     {...P} />,
  flag:     <Flag     {...P} />,
  doc:      <FileText {...P} />,
  car:      <Car      {...P} />,
  building: <Building2 {...P} />,
  device:   <Laptop   {...P} />,
  machine:  <Cog      {...P} />,
  package:  <Package  {...P} />,
};

export const MI = {
  bell:    <Bell          {...MP} />,
  plus:    <Plus          {...MP} />,
  cam:     <Camera        {...MP} />,
  truck:   <Truck         {...MP} />,
  arrowR:  <ArrowRight    {...MP} />,
  chev:    <ChevronRight  {...MP} />,
  back:    <ArrowLeft     {...MP} />,
  more:    <MoreHorizontal {...MP} />,
  home:    <Home          {...MP} />,
  inbox:   <Inbox         {...MP} />,
  profile: <User          {...MP} />,
  search:  <Search        {...MP} />,
  flag:    <Flag          {...MP} />,
  cal:     <Calendar      {...MP} />,
  dollar:  <DollarSign    {...MP} />,
  upload:  <Upload        {...MP} />,
  msg:     <MessageSquare {...MP} />,
  check:   <Check         {...MP} />,
  spark:   <Sparkles      {...MP} />,
  history: <History       {...MP} />,
};
